### ISSUE TITLE
memberList Template modification

### ISSUE THREAD

**Issue by rustykowski** [oveleon/contao-member-extension-bundle#14]
Das Template mod_memberList gibt das Avatarbild und die gewählten Felder als `ul` aus.
Es scheint aber keinerlei Template-Variablen zu geben, mit denen man das Markup selbst definieren kann, oder?
Die einzig verfügbare Variable `$member` enthält bereits das vollständige Markup.

**Comment by eki89** [comment]
Im Listen-Modul kann man das Template für Mitglieder auswählen, welches du einfach übeschreiben kannst. Also equivalent zur Contao News-Liste oder Event-Liste.

Das folgende Template ist vorausgewählt: https://github.com/oveleon/contao-member-extension-bundle/blob/master/contao/templates/member/memberExtension_list_default.html5

**Comment by rustykowski** [comment]
Ah, vielen Dank! Ich hatte Modultemplate und Listentemplate verwechselt.
