### ISSUE TITLE
detailpage throws 404-error

### ISSUE THREAD

**Issue by pindo-bindo** [oveleon/contao-member-extension-bundle#16]
Hi, 

trying your plug-in I encounter that calling the detailpage the system throws an 404-error.

The detailpage "details.html" exists and can be called without error.
Only called from within an entry of the list with the added it (e.g. details/2.html) the error is thrown.

Contao  4.13.30 / php 8.1.22 / MariaDB
contao-member-extension-bundle 1.3

Thanks for helping!

**Comment by zoglo** [comment]
@pindo-bindo

I can not reproduce that issue.

did you update from a previous version or did you just install this bundle?
There is an option called "Groups to show" within the reader-module.

Did you forget adding the groups to that?

**Comment by zoglo** [comment]
- closed as no answer (stale)
