### ISSUE TITLE
Add checkbox to delete image at FE

### ISSUE THREAD

**Issue by zonky2** [oveleon/contao-member-extension-bundle#3]
Add checkbox to delete image at FE

**Comment by zoglo** [comment]
Hey @zonky2  ,

I've added a new module named "Delete avatar" in the version "dev-develop": https://packagist.org/packages/oveleon/contao-member-extension-bundle#dev-develop.

#### Notes:
- make sure to setup the groups within the modules member reader and member list. The old ones were used wrong by mistake (protected groups).
- in case a user didn't upload a picture yet and you did not setup a default picture within the global member settings, there'll be a fallback picture.
- uploaded images will be renamed to "memberAvatar" and their respective filetype.
- deleting the file will also delete it from the member folder

Could you test the version and tell me if it works?

Edit:
The module is only rendered if the member has a profile picture (It's also not a checkbox but a button)
