### ISSUE TITLE
Manual sorting of the memberlist?

### ISSUE THREAD

**Issue by Webstylerin** [oveleon/contao-member-extension-bundle#4]
Is there a way to sort the member list? In my case, I need to sort by zip code.

Regards,
Nicole

**Comment by zoglo** [comment]
Hi @Webstylerin ,

it's currently not possible to sort the results of the member list. Adding an individual sorting for the memberlist shouldn't be a lot of work so we may consider adding it in the future.

**Comment by zoglo** [comment]
Hi @Webstylerin ,

in der Version "dev-develop": https://packagist.org/packages/oveleon/contao-member-extension-bundle#dev-develop gibt es nun die Möglichkeit, dass man in der Mitgliederliste nach einem Feld sortieren kann.

#### Hinweise:
- für die Ausgabe des Mitgliedlesers und der Mitglieder-Liste müssen in der neuen Version die Einstellungen für die Gruppen noch einmal neu gesetzt werden, da vorher fälschlicherweise die protected groups genutzt wurden.
- als Standardprofilbild wird ein Bild aus dem Bundle genutzt, in den Mitgliedseinstellungen in Contao gibt es aber die Möglichkeit ein globales Bild einzustellen. Beide Bilder werden genutzt, wenn der Nutzer kein Profilbild hochgeladen hat.

Könntest du die Version testen und mir sagen ob es bei dir funktioniert?

**Comment by Webstylerin** [comment]
Hallo @zoglo,

sorry für die späte Antwort, mir fehlt aktuell die Zeit zum Testen. Heute habe ich sie mir einfach genommen.

Herzlichen Dank für die Änderungen, habe die dev-develop nun installiert und kann nach PLZ sortieren! Funktioniert wunderbar! 

Dass man die Gruppen in den Modulen noch mal neu setzen muss, hast du ja geschrieben.

Zudem muss man die Listen-Templates noch umbenennen, wenn man eigene hat. Hier hat sich wohl der Name geändert, daher erscheint bei vorhandenen Modulen z. B. "Unbekannte Option: member_list_default".

Ich hatte schon vorher ein eigenes Standard-Profilbild über die Mitglieder-Einstellungen gesetzt. Das funktioniert unverändert. Wenn ich mein eigenes Bild entferne, erscheint aber kein Standardprofilbild. Auch nicht, wenn ich Standard-Templates nutze.

LG
Nicole
