### ISSUE TITLE
Registrierung/Personendaten ->kein Speichern des Profilfotos

### ISSUE THREAD

**Issue by petrad** [oveleon/contao-member-extension-bundle#6]
Hallo,

das Profilfoto wird im Frontend bei der Registrierung und bei Personendaten nicht gespeichert. Es gibt keinerlei Fehlermeldung im System-Log oder var/logs. Der Debug-Modus wirft auch keinen Fehler aus. In der Dateiverwaltung wird das Foto auch nicht gespeichert. 
Habe zum Testen nur noch eine Contao 4.9-Installation, liegt es an 4.9?

LG, Petra

**Comment by zoglo** [comment]
Hey @petrad ,

hast du für den jeweiligen Nutzer die Option 'Ein Home-Verzeichnis anlegen' aktiviert?

Siehe:
https://docs.contao.org/manual/de/benutzerverwaltung/mitglieder/#home-verzeichnis

Ohne Verzeichnis kann kein Bildupload erfolgen. Bestehende Mitglieder müssten im Mitglied selbst angepasst werden, für neue Mitglieder lässt es sich im Modul "Registrierung" unter Konto-Einstellungen aktivieren.

**Comment by petrad** [comment]
Hi @zoglo ,

vielen Dank für Deine schnelle Rückmeldung. 
Genau, ich hatte vergessen zu schreiben, dass ein Home-Verzeichnis angelegt ist. 
Bei einem bestehenden Mitglied funktioniert das Hochladen mit "Personendaten" auch mittlerweile, aber bei der Registrierung wird zwar das Verzeichnis angelegt und ist das Foto z.B. größer als 2 MB, erfolgt auch eine Fehlermeldung. Aber ein Upload erfolgt nicht. Muss noch ein Hook "createNewUser" erfolgen?

LG, Petra

Edit: Mit einem Hook createNewUser analog zu Eurem Member::updateAvatar() klappt es; mit der kleinen Änderung 
$objMember = MemberModel::findByPk($userId);

**Comment by zoglo** [comment]
Hierbei sollte man aufpassen, dass der User schon existiert, da es auch die Möglichkeit eines Double Opt-In Verfahrens gibt. 

Muss mir genauer anschauen ob durch den Hook die Mechanik ausgehebelt wird (Sonst wäre es möglich den Speicher des Servers mit Erstellung vieler neuer Nutzer in die Knie zu zwingen).
Eventuell ist es besser, wenn der Upload erst nach der Registrierung erfolgt?

**Comment by petrad** [comment]
Hallo @zoglo,

vielen Dank für Deinen Hinweis, das war mir in der Tat so nicht bewusst. Habe den createNewUser-Hook trotzdem erst einmal eingerichtet und beim Testen hat es funktioniert. Sollte es keine UserID geben, passiert nichts weiter und bei dem Projekt wäre es nicht sooo tragisch, wenn die Teilnehmer das Profilfoto im Login-Bereich später noch einmal hochladen müssten.

LG, Petra

**Comment by zoglo** [comment]
Hey @petrad ,

habe es soeben wie vorgeschlagen eingebaut, es funktioniert auch.

Da der Hook createNewUser aber eine ID und der Hook updatePersonalData das Member Objekt übermittelt, wird deine Änderung beim Updaten der persönlichen Daten (Ändern des Avatars) nicht richtig funktionieren.

Das Profilbild kann man jedoch durch deinen Vorschlag bei der Registrierung speichern.
Der o.g. Fall ist dann eher Konfigurationssache.

Werde es in der baldigen Version mit einer createAvatar Methode lösen.

**Comment by zoglo** [comment]
Hallo @petrad,

in der Version "dev-develop": https://packagist.org/packages/oveleon/contao-member-extension-bundle#dev-develop habe ich den Fehler behoben. Zusätzlich gibt es nun auch ein weiteres Modul zum Löschen des Bildes.

#### Hinweise:
- für die Ausgabe des Mitgliedlesers und der Mitglieder-Liste müssen in der neuen Version die Einstellungen für die Gruppen noch einmal neu gesetzt werden, da vorher fälschlicherweise die protected groups genutzt wurden.
- als Standardprofilbild wird ein Bild aus dem Bundle genutzt, in den Mitgliedseinstellungen in Contao gibt es aber die Möglichkeit ein globales Bild einzustellen. Beide Bilder werden genutzt, wenn der Nutzer kein Profilbild hochgeladen hat.

Magst du die Version testen und mir sagen ob es bei dir funktioniert?

**Comment by petrad** [comment]
Hallo @zoglo,

vielen vielen vielen lieben Dank für Deine Änderungen, bei dem Kundenprojekt, das noch nicht freigeschaltet wurde, funktioniert die dev-develop wunderbar (habe zuvor meinen Hook deaktiviert)! Beim Registrieren wird das Foto im User-Ordner gespeichert. 
Ein Löschen ist derzeit nicht vorgesehen, nur das Hochladen eines neuen Fotos.
Ist kein Bild hochgeladen, wird auch keines auf der Website ausgegeben, das ist so gewollt.

Vielen Dank!!
Petra

**Comment by marcoheinz** [comment]
Hallo zusammen,

aus aktuellem Anlass hole das Thema nochmal aus dem "Keller" :-)

Habe unter C 4.13.52 und oveleon/contao-member-extension-bundle 1.6.1 das selbe Problem.
Das Home-Verzeichnis des Mitglieds wird bei Registrierung korrekt angelegt.

Beim Hochladen eines Bildes ob Registrierung oder Aktualisierung der Personendaten wird keine Fehlermeldung angezeigt aber das Bild wird nicht gespeichert.

**Comment by codesache** [comment]
@zoglo 
Ich habe unter einer C5.7 eure Erweiterung installiert und kann als FE-User kein Bild hochladen. 
"oveleon/contao-member-extension-bundle": "^1.6"

Als Basis habe ich eine C5.7 Demo verwendet und die Module / FE-Rechte so weit angepasst.
Die Ordner werden angelegt und Berechtigungen passen.
<img width="230" height="218" alt="Image" src="https://github.com/user-attachments/assets/21ad296b-2f8b-4352-9eaa-d20dee91254c" />

Im Debug-Modus kann ich auch nichts sehen, das es beim Upload klemmt. Als Bilder habe ich jpg und gif getestet. 

Kannst du den Upload mal unter einer C5.7 testen oder mir eine Hilfestellung geben wo es klemmt.

**Comment by zoglo** [comment]
@codesache
Ich maintaine diese Erweiterung nicht mehr.

Für Fehler sollten neue Issues geöffnet, für Support eine E-Mail an den Maintainer gesendet werden -> info@oveleon.de
